version: '3.8'
services:
  strapi:
    depends_on:
      - postgres
    build:
      context: ./strapi/
      target: dev
    init: true
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_NAME: strapi
      DATABASE_USERNAME: postgres
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: postgres
      NODE_ENV: development
      APP_KEYS: Vyrg2JxnOrZvJN27fqhdFg==,LTszPxDV1RuEu2ypNbkJTg==,uWV5HfK6rX5+i59RHtXNQA==,g+san15Vano4ZEY8TGB7ZQ==
      API_TOKEN_SALT: 8bgR64I586hkaoD4dj+lJw==
      ADMIN_JWT_SECRET: GB5XbvEvLLaxbg9Ce0qrsw==
      JWT_SECRET: Q83kKZ+i5qdlI5f1lHr7Hw==
    command: yarn develop
    ports:
      - "1337:1337"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: strapi
      PGPORT: 5432
    expose:
      - '5432'
    ports:
      - '127.0.0.1:5432:5432'

volumes:
  postgres: