apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-gallery-strapi-plugin-preview-secret
  namespace: standalone
spec:
  encryptedData:
    STRAPI_PREVIEW_SECRET: AgC5MaKeK57H0kCMdFnGCJhHotGoIEl4rNV7sohYFi5qcQWQnbx/yleKc/013iVvb4Qo9EX4xytbqKiKaEJ08UKFAFr+kA8mwJB7yJ/0fArIEewRemj5lWMjuWIx2w5Mn0xzglqw2cSsXlRvTzddLZ/abafK7REgRe1nVgw6mXoAnnS4UeF1g4OCUPRoQKrzDofGOTbZw1xkqWu/Gu+NvCuJm+ujQUj7nij9DohVQ0OTBP1sDII1eoIcjNxtA0CqgZFth3s39hko8gu9dB3MD5U4t/ywFCwAe54PaQ0YWMQdpN5KbL2dEoMt3rxfnBCzeQs5B4/9+vqiWmjD3KxoBerFYPv+klO8URBGAuLM2yTQhhUlU8H5dP5ABxMS30G0mL8Da3/z0PLGe3/OjLnrzI9AKpcS3HLbOWgsyxJ3i3CRhagTy/Q1UgtMcWdxvwoqpplUlrfS2xnoW4IfT7DiJNyU5RqZUgsoDfm6gzo82xr9vtL73YwHnURs3uyl8d0JdS8rcGMjtUPGQHL9MqhU3TYVVzpglDonFp5OvrybD7YYZ715AEOtxnAnBbojbzWoWuYVmWINaH4P43rXGKuY2BB7zoTOfVN/oFgsayD1/re/ojOtCarB6HFr3yfwM9scu00kCNN5EfT5qHDfToOhBDpbKRSx2Uo5ZzxNhC9xMIfoCpaQHa5cMClGzzmXmB5owOB6ECp1Y+C9slNeOdNMQV1K27wFdnL8D3w=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-gallery-strapi-plugin-preview-secret
      namespace: standalone

