apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-gallery-strapi-plugin-preview-secret
  namespace: standalone
spec:
  encryptedData:
    STRAPI_PREVIEW_SECRET: AgBW6jOL8qmfUlj5YMuY7E7MzXvONW5CtYfL4ng4dKMgFdtND7weQV9+f2K4cDx7pgzdQDUnjfHulDDp1WYORBwpeU+j2AgP9DoM4C0JEDkA0NZFC/8kAS8D7qc5zfttK9lPe2H97FlP47z5GaKe5xmcwp/Ombqn0hVzhyJrGrll+sUqfn/AuCMCu3wIrrFoXgexzFSm7Jv+qEHMDVE5XRrVLYRv8zv1hh6ITbofUviPAzrbgEzNYJuu1ziJ+TVQOmls3dPkqdoEnzpXIqPKd5WtHdb5mcuLuhMVpmnX2eaQEcmLkPByCNa1RDvGIKAVkQSWLGvPi4KfPz36Btohd+jVc0xJNxAWxgEAbCHfY5+UihOj37u1GNw2rdCpyRqwxhuXAwV6FkROyssONdY6IAYGv/kt8/YHCim+CJGMHHjVBRWv945Wo5rv5IKIrDJHcvhYYD7MldnJK7y4J6suJWyqsrVCT/2kpG2d2QCW+Fn1qcZNZEgqVeFirq1ZOXSMVyCNOgncMVA9CeLtVZ0+Mnm6EFQ7s/sQUCDc/v1umh0NAhiDwp8KLZMYfAoNZKlI87btI9Dut042VmobluovjqhtLf0rcAAT8WAvFBXn50El5xGZTVs22ux3eU1QAQe7ENTAqwmi0fSRVo8Ur6YyRTzqN7GgV374cvG9PeV313kexfRb6BXGhCUQwRojV7/GgJF3MbRDZgRo2xSObniZB0Nk53W/3HLAMy9tDh3/QBiZ
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-gallery-strapi-plugin-preview-secret
      namespace: standalone

