apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-gallery-next-general-secret
  namespace: standalone
spec:
  encryptedData:
    STRAPI_PREVIEW_SECRET: AgCLqA2hVw6iTpoJv5JnS8RYLJe+B3bryZQKoEBdRVkGLwYLG/tgWK7xdiuY9ZFwQELQdO/Zr044FBai7QKavxC+aP0x3feMdOaiKFRYdizchy9O/FVHxEdnDDQ72vw2d+Lh0JSw2QZrnH00BHjoCY84OAZDxsTR8jT3tMhuOwR4RcuM9olWdQziSh09rttc75k5JeGvMFJBlgDuhguzjNMVvGiHn+j5vvmTpnEBwTeqIFCY00zIcxWRHnf4L0CbroybJHxb3cX4YTTpaT9v+81/4eYe1EzelwNGZ3BW/00u0BRnQ4M3hfNqlHj4tPpB6CpWL/0ctMCCnESN5FR6XZEtIrQjndPq6CtkqCxtRty2xonTjRCta1YeckPumbsqrIC9MJ8y6oVr16y5iM4KC09y7yADtK6kE/QhI/1rWsCcZydyvRjkd5oudcs48MqEUFyTvs7px6Sm6MWAGjoCnLpZt3APizsbK8RWeN6CwTusonxcotQK+q3uJeZoCV1Wwk7OqS+LneMctYHjSXCgm4Gm2tLMlclNkIJxYNct9gMib4YD05nMrjj1CpP4JLMXw4Gly1uuSmiYF3559EMixIJIy51N2hxuVAYMOTAzyWH5B41DNIQUyjzcCEQhX9wPcCElVcTJZDqyOwKPpCn6wTf0aBQMO5Vay0Zsy1F9YXobhI2faeXmFxnDAyPYONQMTBLMhrI+EV4s9jxArUIEhDTCN86qpO5rkS4HuFrgA5O8
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-gallery-next-general-secret
      namespace: standalone

