apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-gallery-next-general-secret
  namespace: standalone
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgDFRmbMYKc5JvehR0FR0VdV1UqsuGkerbt2BxASx5q6rY8TEFCdoEYdYBiMsgM0rZJMX7d4Wh6x2ky0HNJkVbwS3PlwDVXoY7AXArsGRhgNCqRNl2EWZ8VjZGyXAIXZEm/jYsYzz/SNDbp0kaVWM5wmAnCvB6aZtEfyjq2KdiCkOWrtseX79EfX74ILH4GwnuYbno8sZdUmy/4OsKRj4T2kTRs7UiXcz7csSBV4Dlm7vJmwJ1Ubo+U6GS1bRhtw82RgEAITSzFbNebkZzfKdQU28hgLjooa/4VLHm6YcxjS4FaaXRD0T2BRwq7p8GhTd0vHfqylQ5IlvSNWGvayooY0ocdNMo7UAb/iDtF9R+n7qVPyeSZN4Jul7ptXTWg4YNtfW5W0j62W70k5ImzvZLl3JMxzQDAd1SvXWpBPHPZEeyadBZwqYjXgfjBouYhJHJAkaesaT9H6fJjbG2RyAEOYePL9Fb8z4LHgBYmqFQ7m8mo7aHCvg9sY7HyuV1sLkFUFFzD6373M7GpfYi0JMD3SZMFssvDg6J+8Zs1dsYN7AQQL3cpau20kJMd0qApjYRoQSrQ+HgnHvJVYVcfpjKpb00tNiyxeZ28Inr6j+7WgFo30qgCn1KGRbrA0q1pvya7bvEnGHIgPmQUZeEbFBqUkzOFdfXTRRvaFYdoYR0eA/POJqJgDuK6BXrsbQwlSgW8VrdIwHP9P6QuBq5ahkk1obL9oW5u75HANh4Ilkhk/Sg==
    STRAPI_PREVIEW_SECRET: AgCdNDHqam4Bof8r9ipNajFmXi4n9Ug4xR4ZBmAhuDYQBNdbYBoxjQZdVo0aJG2HseJ3epVf83HqY/OMPFX7J/O/pVRBIIQCbaggYtEL9M2U2HnvNZ2eN1QgP6gBEvG5W/MfQveV6kTtbx0B+fL4nG8ALXMiunPqvlaVp4ipq9Tit17gTuOUvwtc16k9AFGHUZx5paqjqsKTA6Pe6HJIJ5VPLBGUGLG+9fPw8tFrsGqAtK4VLQg2PW/7gNvxcoyYbW3fxQMXWjshw1WVcYS4Fe2kL7MoKeXRV/JFV7zfPgB5fjYXJJYVeD638pXRTttc5XVyaMtGLY+PqOFKxqgSTH45qYzaRoos3X7EwEVKNYb2ssa6TfUPwAejyuN6i1LnD5iMjJrIyduUVDY+G1uxS5ik+nGfuIQzqLE1K2auQMVtxXmJwes/m46FSqCmiAcQ2gDKrCnbY2UbRu7Z0NNheMrBKLl7GHz4/TuopniF8Icmrx1GtDHpSUnT29oo//5SwnuuWIzBaXTLsY2KIBjHcQpwW+oOhQZfl80yF5ZPg0apLMC+7v9L7ZpbU/tJRz1p9/m9YI0k9Aflx9WpPxiv22ypl+XTtDXpY+GE+IcQtiy3rh0XDLm2cSTKuL1eYHhotP5vDkhs2ZziUeKHRpJVz9vv+4rxOk8pSu6FXgl0wCkvxlNbumxCzbnKhF+j/80kN3sc4a79m8Je/gd1oSyZ436t5uf+HWx/D60=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-gallery-next-general-secret
      namespace: standalone

